language: node_js
node_js:
  - "12.4.0"
cache:
  directories:
    - node_modules

before_script:
  - if [ $TRAVIS_BRANCH == "dev" ]; then
      echo REACT_APP_URL=https://dev.hackillinois.org > .env;
    else
      echo REACT_APP_URL=https://hackillinois.org > .env;
    fi

  - echo REACT_APP_EMAILJS_TEMPLATE_ID=$EMAILJS_TEMPLATE_ID > .env
  - echo REACT_APP_EMAILJS_USER_ID=$EMAILJS_USER_ID > .env;
  
  - npm install
script:
  - npm run lint
  - npm run build

deploy:
 - provider: s3
   access_key_id: $ACCESS_KEY_ID
   secret_access_key: $SECRET_ACCESS_KEY
   bucket: $DEV_BUCKET
   skip_cleanup: true
   local_dir: build
   on:
    branch: dev
 - provider: s3
   access_key_id: $ACCESS_KEY_ID
   secret_access_key: $SECRET_ACCESS_KEY
   bucket: $MASTER_BUCKET
   skip_cleanup: true
   local_dir: build
   on:
    branch: master
