language: node_js
node_js:
  - "12.4.0"
cache:
  directories:
    - node_modules

before_script:
  - echo REACT_APP_URL=https://2020.hackillinois.org > .env;
  - npm install
script:
  - npm run lint
  - npm run build

deploy:
 - provider: s3
   access_key_id: $ACCESS_KEY_ID
   secret_access_key: $SECRET_ACCESS_KEY
   bucket: $BUCKET
   skip_cleanup: true
   local_dir: build
   on:
    branch: master
